############# English navigation ##############

# main menu

[[main]]
weight = 3
name = "Company"
hasChildren = true

[[main]]
weight = 1
parent = "Company"
name = "About Us"
url = "about/"

[[main]]
weight = 1
parent = "Company"
name = "How it Works"
url = "how-it-works/"

[[main]]
weight = 2
parent = "Company"
name = "FAQ"
url = "faqs/"

[[main]]
weight = 3
parent = "Company"
name = "Terms & Conditions"
url = "tnc/"

[[main]]
weight = 4
parent = "Company"
name = "Money Back"
url = "money-back/"

[[main]]
weight = 5
parent = "Company"
name = "Revision Policy"
url = "revision-policy/"

[[main]]
weight = 6
parent = "Company"
name = "Privacy Policy"
url = "privacy-policy/"

[[main]]
weight = 7
parent = "Company"
name = "Testimonials"
url = "testimonials/"

[[main]]
name = "Pricing"
url = "pricing/"
weight = 4

[[main]]
weight = 5
name = "Services"
hasChildren = true

[[main]]
weight = 1
parent = "Services"
name = "Entire Online Class Help"
url = "services/entire-online-class-help"

[[main]]
weight = 1
parent = "Services"
name = "Exam Help service"
url = "services/exam-help-service"

[[main]]
weight = 2
parent = "Services"
name = "General Writing Service"
url = "services/general-writing-service"

[[main]]
weight = 3
parent = "Services"
name = "Original Assignment Help"
url = "services/original-assignment-help"

[[main]]
name = "Contact Us"
url = "contact/"
weight = 7


# footer menus
[[about]]
name = "Our Story"
url = "about/"
weight = 1

[[about]]
name = "Testimonials"
url = "testimonials/"
weight = 2

[[about]]
name = "How It Works"
url = "how-it-works/"
weight = 3



[[service]]
name = "Entire Online Class Help"
url = "services/entire-online-class-help"
weight = 1

[[service]]
name = "Exam Help service"
url = "services/exam-help-service"
weight = 2

[[service]]
name = "General Writing Service"
url = "services/general-writing-service"
weight = 3

[[service]]
name = "Original Assignment Help"
url = "services/original-assignment-help"
weight = 4


[[help]]
name = "Pricing"
url = "pricing/"
weight = 1

[[help]]
name = "Blog"
url = "blog/"
weight = 2

[[help]]
name = "Contact"
url = "contact/"
weight = 4

[[legal]]
name = "Terms"
url = "tnc/"
weight = 1

[[legal]]
name = "Money Back"
url = "money-back/"
weight = 2

[[legal]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[legal]]
name = "Revision Policy"
url = "revision-policy/"
weight = 4
