############# English navigation ##############

# main menu
[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 3

[[main]]
name = "Features"
url = "features/"
weight = 4

[[main]]
weight = 6
name = "Pages"
hasChildren = true

[[main]]
weight = 1
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
weight = 1
parent = "Pages"
name = "Pricing"
url = "pricing/"

[[main]]
weight = 2
parent = "Pages"
name = "Testimonials"
url = "testimonials/"

[[main]]
weight = 3
parent = "Pages"
name = "Elements"
url = "elements/"

[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menus
[[about]]
name = "Our Story"
url = "about/"
weight = 1

[[about]]
name = "Testimonials"
url = "testimonials/"
weight = 2

[[about]]
name = "How It Works"
url = "how-it-works/"
weight = 3



[[service]]
name = "Entire Online Class Help"
url = "services/entire-online-class-help"
weight = 1

[[service]]
name = "Exam Help service"
url = "services/exam-help-service"
weight = 2

[[service]]
name = "General Writing Service"
url = "services/general-writing-service"
weight = 3

[[service]]
name = "Original Assignment Help"
url = "services/original-assignment-help"
weight = 4


[[help]]
name = "Pricing"
url = "pricing/"
weight = 1

[[help]]
name = "Blog"
url = "blog/"
weight = 2

[[help]]
name = "Contact"
url = "contact/"
weight = 4

[[legal]]
name = "Terms"
url = "tnc/"
weight = 1

[[legal]]
name = "Money Back"
url = "money-back/"
weight = 2

[[legal]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[legal]]
name = "Revision Policy"
url = "revision-policy/"
weight = 4
